export const API = {
  LOGIN: '/api/login',
  FORGOT_PASSWORD: '/api/forgot-password',
  RESET_PASSWORD: '/api/reset-password',
  CUSTOMERS: '/api/customers',
  CUSTOMER_ACTION: (id, action) => `/api/customers/users/${id}/${action}`,
  CUSTOMER_DELETE: (id) => `/api/customers/users/${id}`,
  ADMIN_SETTINGS: '/api/admin/settings',
};

export const CACHE_KEYS = {
  CUSTOMERS: 'customers_list',
  ADMIN_SETTINGS: 'admin_settings',
  SMS_PROVIDERS: 'sms_providers',
  SMS_TEMPLATES: 'sms_templates',
  SMS_JOBS: 'sms_jobs',
  EMAIL_PROVIDERS: 'email_providers',
  EMAIL_TEMPLATES: 'email_templates',
  EMAIL_JOBS: 'email_jobs',
  WHATSAPP_PROVIDERS: 'whatsapp_providers',
  WHATSAPP_TEMPLATES: 'whatsapp_templates',
  WHATSAPP_JOBS: 'whatsapp_jobs',
  VOTERS: 'voters',
  COUNTIES: 'counties',
  PRECINCTS: 'precincts',
  LISTS: 'contact_lists',
  USERS: 'users',
  ROLES: 'roles',
  PERMISSIONS: 'permissions',
  DASHBOARD: 'dashboard_stats',
};
