"""initial

Revision ID: 976528942561
Revises: 
Create Date: 2026-05-22 23:20:41.646872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '976528942561'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - No changes."""
    # This migration is intentionally left empty to set the baseline.
    pass


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_templates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('subject', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'email_templates', ['code'], unique=True)
    op.create_table('whatsapp_jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('precinct_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('scheduled_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('recipients', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['precinct_id'], ['precincts.id'], name=op.f('whatsapp_jobs_ibfk_1')),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], name=op.f('whatsapp_jobs_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('whatsapp_providers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), server_default=sa.text("'Twilio'"), nullable=True),
    sa.Column('account_sid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('auth_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('from_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'whatsapp_providers', ['code'], unique=True)
    op.create_table('sms_jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('precinct_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('scheduled_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('recipients', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['precinct_id'], ['precincts.id'], name=op.f('sms_jobs_ibfk_1')),
    sa.ForeignKeyConstraint(['template_id'], ['sms_templates.id'], name=op.f('sms_jobs_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('email_providers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), server_default=sa.text("'SMTP'"), nullable=True),
    sa.Column('smtp_host', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_port', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('smtp_user', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('smtp_pass', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('config_email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'email_providers', ['code'], unique=True)
    op.create_table('email_jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('precinct_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('template_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('provider_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('scheduled_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('recipients', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['precinct_id'], ['precincts.id'], name=op.f('email_jobs_ibfk_1')),
    sa.ForeignKeyConstraint(['template_id'], ['email_templates.id'], name=op.f('email_jobs_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('precincts',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('county_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('zipcode', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['county_id'], ['counties.id'], name=op.f('precincts_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'precincts', ['code'], unique=True)
    op.create_table('sms_providers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=50), server_default=sa.text("'Twilio'"), nullable=True),
    sa.Column('priority', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('account_sid', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('auth_token', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('from_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'sms_providers', ['code'], unique=True)
    op.create_table('permissions',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('code', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('resource_path', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('resource_type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('parent_menu', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('icon', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('display_order', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'permissions', ['code'], unique=True)
    op.create_table('voters',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('precinct_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['precinct_id'], ['precincts.id'], name=op.f('voters_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('counties',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('state', mysql.VARCHAR(length=50), server_default=sa.text("'GA'"), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'counties', ['code'], unique=True)
    op.create_table('whatsapp_templates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'whatsapp_templates', ['code'], unique=True)
    op.create_table('roles',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'roles', ['code'], unique=True)
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), server_default=sa.text("'User'"), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('username'), 'users', ['username'], unique=True)
    op.create_table('sms_templates',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'Active'"), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('code'), 'sms_templates', ['code'], unique=True)
    # ### end Alembic commands ###
